name: Bug report
description: Report a reproducible problem
title: "bug: "
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Pre-flight
      options:
        - label: I searched existing issues
          required: true
        - label: I can reproduce this consistently
          required: true
  - type: textarea
    attributes:
      label: What happened?
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Provide the minimal steps to reproduce the issue.
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: OS, terminal, Zellij, Yazi, Rust, and any relevant versions.
      value: |
        OS:
        Terminal:
        Zellij:
        Yazi:
        Rust:
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs or screenshots
      description: Redact any secrets.
    validations:
      required: false
